######################################################################
# Automatically generated by qmake (2.01a) tor. jan. 27 22:59:45 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += core

# Input
SOURCES += main.cpp
